// tag_dict.js
// DLsite ジャンル/タグ 日本語→英語 対訳辞書
// 公式タグ一覧（こだわり/アピール・シチュエーション/系統・プレイ/えっち傾向・
// アイテム/道具・キャラクター/衣装・外見/身体的特徴・R-18G/マニア）のみを収録。
// content.js から参照される（同一 content_scripts 内でグローバル公開）

const TAG_EN = {
  // ── こだわり/アピール ──
  "3D作品": "3D Work",
  "ASMR": "ASMR",
  "RPGBakin": "RPG Dev Bakin",
  "TRPG": "TRPG",
  "TRPGシナリオ": "TRPG Scenario",
  "TRPGリプレイ集": "TRPG Replay",
  "TRPGルールブック": "TRPG Rulebook",
  "VTuber": "VTuber",
  "脚": "Legs",
  "アニメ": "Animated",
  "アヘ顔": "Ahegao",
  "アンソロジー": "Anthology",
  "癒し": "Healing",
  "淫語": "Dirty Talk",
  "鬱": "Depressing",
  "オールハッピー": "All Happy End",
  "おさわり": "Groping",
  "お尻/ヒップ": "Ass/Hips",
  "おっぱい": "Breasts",
  "男主人公": "Male Protagonist",
  "女主人公": "Female Protagonist",
  "感動": "Moving",
  "技術書": "Technical Book",
  "きせかえ": "Dress-up",
  "逆転無し": "No Reversal",
  "女性視点": "Female POV",
  "シリーズもの": "Series",
  "汁/液大量": "Lots of Fluids",
  "総集編": "Compilation",
  "淡白/あっさり": "Mild",
  "断面図": "Cross-section",
  "着衣": "Clothed",
  "チラリズム": "Peek-a-boo",
  "ツクール": "RPG Maker",
  "東方Project": "Touhou Project",
  "ドット": "Pixel Art",
  "トランス/暗示ボイス": "Trance/Hypno Voice",
  "バイノーラル/ダミヘ": "Binaural/Dummy Head",
  "評論": "Critique",
  "フェチ": "Fetish",
  "マニアック/変態": "Maniac/Perverted",
  "萌え": "Moe",
  "燃え": "Thrilling",
  "連続絶頂": "Continuous Orgasm",

  // ── シチュエーション/系統 ──
  "BSS": "BSS",
  "SF": "Sci-Fi",
  "色仕掛け": "Seduction",
  "淫紋": "Lewd Mark",
  "浮気": "Cheating",
  "オカルト": "Occult",
  "屋外": "Outdoors",
  "おねショタ": "Onee x Shota",
  "オフィス/職場": "Office/Workplace",
  "おもらし": "Wetting",
  "快楽堕ち": "Pleasure Corruption",
  "格闘": "Fighting",
  "学校/学園": "School",
  "感覚遮断": "Sensory Deprivation",
  "ギャグ": "Gag",
  "逆NTR": "Reverse NTR",
  "逆アナル": "Reverse Anal",
  "キャットファイト": "Catfight",
  "恋人同士": "Lovers",
  "コメディ": "Comedy",
  "サスペンス": "Suspense",
  "時間停止": "Time Stop",
  "純愛": "Pure Love",
  "常識改変": "Reality Alteration",
  "ショタおね": "Shota x Onee",
  "シリアス": "Serious",
  "人格排泄": "Personality Purge",
  "睡眠導入": "Sleep-inducing",
  "スポーツ": "Sports",
  "スワッピング": "Swapping",
  "性転換(TS)": "Gender Swap (TS)",
  "石化": "Petrification",
  "戦場": "Battlefield",
  "戦闘エロ": "Battle Ecchi",
  "添い寝": "Sleeping Together",
  "ソフトエッチ": "Soft Ecchi",
  "退廃/背徳/インモラル": "Decadent/Immoral",
  "電車": "Train",
  "同居": "Living Together",
  "同棲": "Cohabitation",
  "歳の差": "Age Gap",
  "日常/生活": "Daily Life",
  "女体化": "Genderbend (F)",
  "寝取らせ": "Netorase",
  "寝取られ": "Netorare",
  "寝取り": "Netori",
  "ノンフィクション/体験談": "Nonfiction/Experience",
  "ハーレム": "Harem",
  "バイオレンス": "Violence",
  "売春/援交": "Prostitution",
  "初体験": "First Time",
  "憑依": "Possession",
  "ファンタジー": "Fantasy",
  "風俗/ソープ": "Sex Work/Soapland",
  "ほのぼの": "Heartwarming",
  "ホラー": "Horror",
  "マッサージ": "Massage",
  "魔法": "Magic",
  "丸呑み": "Vore",
  "ミステリー": "Mystery",
  "耳かき": "Ear Cleaning",
  "ミリタリー": "Military",
  "百合": "Yuri",
  "ラブコメ": "Rom-Com",
  "ラブラブ/あまあま": "Lovey-dovey",
  "料理/グルメ": "Cooking/Gourmet",
  "歴史/時代物": "Historical",
  "男性間接触": "Male-Male Contact",
  "女性間接触": "Female-Female Contact",

  // ── プレイ/えっち傾向 ──
  "SM": "BDSM",
  "青姦": "Outdoor Sex",
  "悪堕ち": "Corruption",
  "足コキ": "Footjob",
  "アナル": "Anal",
  "異種えっち": "Interspecies Sex",
  "イラマチオ": "Deepthroat",
  "淫乱": "Nympho",
  "オナサポ": "JOI",
  "オナニー": "Masturbation",
  "オホ声": "Guttural Moans",
  "顔射": "Facial",
  "浣腸": "Enema",
  "機械責め": "Machine Torture",
  "キス": "Kiss",
  "亀頭責め": "Glans Torture",
  "逆レ": "Reverse Rape",
  "近親もの": "Incest",
  "緊縛": "Bondage (Rope)",
  "くすぐり": "Tickling",
  "屈辱": "Humiliation",
  "クリ責め": "Clit Torture",
  "ゲイ/男同士": "Gay",
  "下克上": "Reversal of Fortune",
  "ゲップ": "Burping",
  "下僕": "Servant",
  "合意なし": "Non-consensual",
  "拘束": "Restraint",
  "口内射精": "Cum in Mouth",
  "ごっくん/食ザー": "Swallowing",
  "言葉責め": "Verbal Abuse",
  "搾乳": "Milking",
  "ささやき": "Whispering",
  "産卵": "Egg Laying",
  "潮吹き": "Squirting",
  "しつけ": "Training",
  "羞恥/恥辱": "Shame/Humiliation",
  "出産": "Childbirth",
  "触手": "Tentacles",
  "焦らし": "Teasing",
  "スパンキング": "Spanking",
  "すやすやえっち": "Sleeping Sex",
  "精神支配": "Mind Control",
  "男性受け": "Male Bottom",
  "畜えち": "Livestock Sex",
  "乳首責め": "Nipple Torture",
  "超ひどい": "Extremely Cruel",
  "手コキ": "Handjob",
  "盗撮": "Voyeurism",
  "閉じ込め": "Confinement",
  "トランス/暗示": "Trance/Hypnosis",
  "中出し": "Creampie",
  "尿道": "Urethra",
  "妊娠/孕ませ": "Pregnancy/Impregnation",
  "ノーマルプレイ": "Normal Play",
  "パイズリ": "Paizuri",
  "秘密さわさわ": "Secret Touching",
  "フェラチオ": "Fellatio",
  "複数プレイ/乱交": "Group/Orgy",
  "ぶっかけ": "Bukkake",
  "放置プレイ": "Neglect Play",
  "膨乳": "Breast Expansion",
  "放尿/おしっこ": "Urination",
  "母乳": "Breast Milk",
  "本番なし": "No Penetration",
  "回し": "Gangbang Rotation",
  "耳舐め": "Ear Licking",
  "耳ふー": "Ear Blowing",
  "虫えっち": "Insect Sex",
  "命令/無理矢理": "Command/Forced",
  "モブおじさん": "Mob Old Man",
  "レズ/女同士": "Lesbian",
  "露出": "Exposure",
  "和姦": "Consensual Sex",

  // ── アイテム/道具 ──
  "おむつ": "Diaper",
  "おもちゃ": "Toys",
  "首輪/鎖/拘束具": "Collar/Chain/Restraints",
  "道具/異物": "Tools/Foreign Objects",
  "ピアス/装飾品": "Piercing/Accessories",
  "ムチ/縄/蝋燭": "Whip/Rope/Candle",
  "薬物": "Drugs",
  "ローション": "Lotion",

  // ── キャラクター/衣装 ──
  "OL": "Office Lady",
  "妹": "Little Sister",
  "ウェイトレス": "Waitress",
  "エプロン": "Apron",
  "エルフ/妖精": "Elf/Fairy",
  "幼なじみ": "Childhood Friend",
  "お嬢様": "Ojou-sama",
  "男の娘": "Otokonoko",
  "お姉さん": "Onee-san",
  "おやじ": "Old Man",
  "女教師": "Female Teacher",
  "ガーター": "Garter",
  "外国人": "Foreigner",
  "学生": "Student",
  "既婚者": "Married",
  "義姉": "Older Stepsister",
  "擬人化": "Personification",
  "義母": "Stepmother",
  "義妹": "Younger Stepsister",
  "着物/和服": "Kimono",
  "ギャル": "Gal",
  "教師": "Teacher",
  "靴下": "Socks",
  "くノ一": "Kunoichi",
  "軍服": "Military Uniform",
  "警察/刑事": "Police/Detective",
  "芸能人/アイドル/モデル": "Celebrity/Idol/Model",
  "けもの/獣化": "Beastification",
  "コスプレ": "Cosplay",
  "ゴスロリ": "Gothic Lolita",
  "ざぁ～こ♡": "Weakling♡",
  "サキュバス/淫魔": "Succubus",
  "シスター": "Sister (Nun)",
  "下着": "Underwear",
  "実姉": "Older Sister",
  "姉妹": "Sisters",
  "熟女": "Mature Woman",
  "主従": "Master/Servant",
  "女医": "Female Doctor",
  "女王様/お姫様": "Queen/Princess",
  "少女": "Girl",
  "少年": "Boy",
  "女装": "Crossdressing",
  "ショタ": "Shota",
  "人外娘/モンスター娘": "Monster Girl",
  "スーツ": "Suit",
  "スクール水着": "School Swimsuit",
  "ストッキング": "Stockings",
  "スパッツ": "Spats",
  "制服": "Uniform",
  "セーラー服": "Sailor Uniform",
  "戦士": "Warrior",
  "先輩/後輩": "Senior/Junior",
  "ゾンビ": "Zombie",
  "体育会系/スポーツ選手": "Athletic Type",
  "体操着": "Gym Clothes",
  "ダウナー": "Downer",
  "つるぺた": "Flat Chest",
  "つるぺたババア": "Flat Old Woman",
  "ツンデレ": "Tsundere",
  "天使/悪魔": "Angel/Devil",
  "天然": "Airhead",
  "同級生/同僚": "Classmate/Coworker",
  "年上": "Older",
  "ナース": "Nurse",
  "ニーソックス": "Knee-highs",
  "ニューハーフ": "Trans Woman",
  "バニーガール": "Bunny Girl",
  "母親": "Mother",
  "パンツ": "Panties",
  "ビッチ": "Bitch",
  "人妻": "Married Woman",
  "双子": "Twins",
  "ぷに": "Squishy",
  "不良/ヤンキー": "Delinquent",
  "ブルマ": "Bloomers",
  "変身ヒロイン": "Transforming Heroine",
  "ボクっ娘": "Tomboy (Boku)",
  "保健医": "School Nurse",
  "ボンデージ": "Bondage",
  "魔法少女": "Magical Girl",
  "魔法使い/魔女": "Wizard/Witch",
  "巫女": "Miko",
  "水着": "Swimsuit",
  "ミニスカ": "Miniskirt",
  "未亡人": "Widow",
  "娘": "Daughter",
  "メイド": "Maid",
  "メガネ": "Glasses",
  "ヤクザ/裏社会": "Yakuza/Underworld",
  "ヤンデレ": "Yandere",
  "幽霊": "Ghost",
  "妖怪": "Yokai",
  "ラバー": "Rubber",
  "レオタード": "Leotard",
  "レスラー/格闘家": "Wrestler/Fighter",
  "ロボット/アンドロイド": "Robot/Android",

  // ── 外見/身体的特徴 ──
  "陰毛/腋毛": "Pubic/Armpit Hair",
  "褐色/日焼け": "Tanned",
  "巨根": "Big Penis",
  "巨大化": "Giant/Growth",
  "巨乳/爆乳": "Big Breasts",
  "筋肉": "Muscle",
  "金髪": "Blonde",
  "黒髪": "Black Hair",
  "獣耳": "Animal Ears",
  "ショートカット": "Short Hair",
  "処女": "Virgin",
  "スレンダー": "Slender",
  "乳首/乳輪": "Nipples/Areola",
  "長身": "Tall",
  "ツインテール": "Twintails",
  "ツルペタ": "Flat Chest",
  "童貞": "Male Virgin",
  "ネコミミ": "Cat Ears",
  "パイパン": "Shaved",
  "貧乳/微乳": "Small Breasts",
  "複乳/怪乳/超乳": "Bizarre Breasts",
  "フタナリ": "Futanari",
  "太め/デブ": "Chubby",
  "包茎": "Uncircumcised",
  "方言": "Dialect",
  "ぼて腹/妊婦": "Pregnant Belly",
  "ポニーテール": "Ponytail",
  "ムチムチ": "Plump",
  "無表情": "Expressionless",
  "ロングヘア": "Long Hair",

  // ── R-18G/マニア ──
  "拡張": "Expansion",
  "狂気": "Madness",
  "血液/流血": "Blood",
  "人体改造": "Body Modification",
  "スカトロ": "Scat",
  "責め苦": "Torment",
  "ニプルファック": "Nipple Fuck",
  "腹パン": "Stomach Punch",
  "フィストファック": "Fisting",
  "猟奇": "Grotesque",
  "リョナ": "Ryona",
};

// 直マッチしない場合は括弧・件数表記など末尾補足を除去して再検索
function lookupTagEN(raw) {
  if (!raw) return null;
  const key = raw.trim();
  if (TAG_EN[key]) return TAG_EN[key];
  const stripped = key.replace(/[\s　]*[\(（]\s*[\d,]+\s*[\)）]\s*$/, "").trim();
  if (stripped !== key && TAG_EN[stripped]) return TAG_EN[stripped];
  return null;
}
